// Auto-generated Audio Asset Map (do not edit — run: npm run audio:generate)
export const audioMap = {
  "Welcome to Percentage Increase and Decrease! Ready to see how prices, scores, and crowds go up and down? Let's roll!": "/assets/audio/home_intro.mp3",
  "key:home_intro": "/assets/audio/home_intro.mp3",
  "Robo spots a game that costs one hundred dollars. The shop raises the price by twenty percent, then a sale cuts the new price by twenty percent. Alex says: \"Up twenty percent and down twenty percent cancel out, so the price must be back to one hundred dollars.\" Is that actually true? Remember, every percentage change is worked out from the amount you START with!": "/assets/audio/wonder_prompt.mp3",
  "key:wonder_prompt": "/assets/audio/wonder_prompt.mp3",
  "What if the sale came first and the price rise second? Would the answer change?": "/assets/audio/wonder_teaser.mp3",
  "key:wonder_teaser": "/assets/audio/wonder_teaser.mp3",
  "Every change has three parts: the Original amount you start with, the Change, and the New amount. If the new amount is bigger, it is an increase. If it is smaller, it is a decrease. Percent means out of one hundred, so a percentage change tells us how big the change is compared with the original!": "/assets/audio/story_slide_1.mp3",
  "key:story_slide_1": "/assets/audio/story_slide_1.mp3",
  "To find a percentage change, first find the change by subtracting. Then divide the change by the ORIGINAL amount and multiply by one hundred. A game goes from forty dollars to fifty dollars. The change is ten dollars. Ten divided by forty equals zero point two five. Multiply by one hundred to get twenty-five percent. So the price went up by twenty-five percent!": "/assets/audio/story_slide_2.mp3",
  "key:story_slide_2": "/assets/audio/story_slide_2.mp3",
  "Detective Time! A jacket costs eighty dollars after a twenty percent discount. What was the original price? After the discount you pay eighty percent of the original. If eighty percent is eighty dollars, then ten percent is ten dollars. So the full one hundred percent is one hundred dollars!": "/assets/audio/story_slide_3.mp3",
  "key:story_slide_3": "/assets/audio/story_slide_3.mp3",
  "Real world alert! A shop raises the price of a game from one hundred dollars by twenty percent to one hundred twenty dollars. Then a sale cuts twenty percent off the new price. That takes off twenty-four dollars, not twenty dollars, because twenty percent of one hundred twenty dollars is twenty-four dollars. The final price is ninety-six dollars, not one hundred dollars! Every percentage works from the amount you START that step with.": "/assets/audio/story_slide_4.mp3",
  "key:story_slide_4": "/assets/audio/story_slide_4.mp3",
  "Welcome to the Percent Change Lab! Drag the knob on the new bar to make it bigger or smaller. Watch the change, the percent change, and the multiplier update live!": "/assets/audio/station_a_intro.mp3",
  "key:station_a_intro": "/assets/audio/station_a_intro.mp3",
  "Station B: The Multiplier Machine! Choose increase or decrease, turn the dial to a percent, and press Run. Can you make the machine turn the starting amount into the target amount?": "/assets/audio/station_b_intro.mp3",
  "key:station_b_intro": "/assets/audio/station_b_intro.mp3",
  "Station C: The Bar Model Detective! Each block is ten percent. Count the blocks, find what one block is worth, and work backwards to find the original amount.": "/assets/audio/station_c_intro.mp3",
  "key:station_c_intro": "/assets/audio/station_c_intro.mp3",
  "Station D: The Up and Down Lab! Chain two percent changes together and see the final amount. Then try to get exactly back to where you started!": "/assets/audio/station_d_intro.mp3",
  "key:station_d_intro": "/assets/audio/station_d_intro.mp3",
  "It's a match! The machine turned the starting amount into the target. You found the percent change!": "/assets/audio/machine_match.mp3",
  "key:machine_match": "/assets/audio/machine_match.mp3",
  "Not quite yet. Look at the change between the start and the target, then adjust the dial and run again!": "/assets/audio/machine_miss.mp3",
  "key:machine_miss": "/assets/audio/machine_miss.mp3",
  "Case solved! Great detective work. You found the original amount!": "/assets/audio/case_solved.mp3",
  "key:case_solved": "/assets/audio/case_solved.mp3",
  "Exactly back to the start! You found the decrease that undoes the increase!": "/assets/audio/back_to_start.mp3",
  "key:back_to_start": "/assets/audio/back_to_start.mp3",
  "Choose your world on the map! Beat each world to unlock the next. Earn stars and XP!": "/assets/audio/practice_welcome.mp3",
  "key:practice_welcome": "/assets/audio/practice_welcome.mp3",
  "Awesome job! You got it right!": "/assets/audio/correct_cheer.mp3",
  "key:correct_cheer": "/assets/audio/correct_cheer.mp3",
  "Not quite. Remember, a percentage change is always worked out from the original amount!": "/assets/audio/incorrect_try_again.mp3",
  "key:incorrect_try_again": "/assets/audio/incorrect_try_again.mp3",
  "Oh no! Out of hearts! Don't worry, try again to master this world!": "/assets/audio/out_of_hearts.mp3",
  "key:out_of_hearts": "/assets/audio/out_of_hearts.mp3",
  "Congratulations! You completed the world and earned new stars!": "/assets/audio/world_complete.mp3",
  "key:world_complete": "/assets/audio/world_complete.mp3",
  "Your Performance! Amazing work! Let's reflect on what you learned.": "/assets/audio/reflect_intro.mp3",
  "key:reflect_intro": "/assets/audio/reflect_intro.mp3",
  "How do you find a percentage increase or decrease?": "/assets/audio/reflect_q1.mp3",
  "key:reflect_q1": "/assets/audio/reflect_q1.mp3",
  "Subtract to find the change, divide the change by the ORIGINAL amount, then multiply by one hundred. That is (Change divided by Original) times one hundred!": "/assets/audio/reflect_a1.mp3",
  "key:reflect_a1": "/assets/audio/reflect_a1.mp3",
  "What is the golden rule about the base of a percentage change?": "/assets/audio/reflect_q2.mp3",
  "key:reflect_q2": "/assets/audio/reflect_q2.mp3",
  "A percentage change is always measured from the original amount, the amount you started with!": "/assets/audio/reflect_a2.mp3",
  "key:reflect_a2": "/assets/audio/reflect_a2.mp3",
  "How can a multiplier help you find a new amount quickly?": "/assets/audio/reflect_q3.mp3",
  "key:reflect_q3": "/assets/audio/reflect_q3.mp3",
  "For an increase, multiply by one plus the percent. For a decrease, multiply by one minus the percent. So plus twenty percent is times one point two and minus twenty percent is times zero point eight!": "/assets/audio/reflect_a3.mp3",
  "key:reflect_a3": "/assets/audio/reflect_a3.mp3",
  "Why does plus twenty percent followed by minus twenty percent not bring you back to the start?": "/assets/audio/reflect_q4.mp3",
  "key:reflect_q4": "/assets/audio/reflect_q4.mp3",
  "The twenty percent decrease is taken from the bigger, new amount, so it takes off more than the increase added. One hundred times one point two times zero point eight equals ninety-six!": "/assets/audio/reflect_a4.mp3",
  "key:reflect_a4": "/assets/audio/reflect_a4.mp3",
  "How do you find the original amount when you know the new amount and the percent change?": "/assets/audio/reflect_q5.mp3",
  "key:reflect_q5": "/assets/audio/reflect_q5.mp3",
  "Divide the new amount by the multiplier. If a twenty-five percent increase gives one hundred dollars, the original is one hundred divided by one point two five equals eighty dollars!": "/assets/audio/reflect_a5.mp3",
  "key:reflect_a5": "/assets/audio/reflect_a5.mp3",
  "Where can you see percentage increase and decrease in real life?": "/assets/audio/reflect_q6.mp3",
  "key:reflect_q6": "/assets/audio/reflect_q6.mp3",
  "Sale discounts, population growth, savings and interest, phone battery levels, and price rises!": "/assets/audio/reflect_a6.mp3",
  "key:reflect_a6": "/assets/audio/reflect_a6.mp3",
  "A video game costs fifty dollars. After a price rise it costs sixty dollars. What is the increase in price?": "/assets/audio/w1_q1_prompt.mp3",
  "key:w1_q1_prompt": "/assets/audio/w1_q1_prompt.mp3",
  "Increase equals New price minus Original price. Subtract sixty minus fifty.": "/assets/audio/w1_q1_hint.mp3",
  "key:w1_q1_hint": "/assets/audio/w1_q1_hint.mp3",
  "A shirt was eighty dollars. In a sale it costs seventy-two dollars. What is the decrease in price?": "/assets/audio/w1_q2_prompt.mp3",
  "key:w1_q2_prompt": "/assets/audio/w1_q2_prompt.mp3",
  "Decrease equals Original price minus New price. Subtract eighty minus seventy-two.": "/assets/audio/w1_q2_hint.mp3",
  "key:w1_q2_hint": "/assets/audio/w1_q2_hint.mp3",
  "A bus ticket rises from two dollars to three dollars. Which number is the ORIGINAL amount?": "/assets/audio/w1_q3_prompt.mp3",
  "key:w1_q3_prompt": "/assets/audio/w1_q3_prompt.mp3",
  "The original amount is the one you START with, before the change happens.": "/assets/audio/w1_q3_hint.mp3",
  "key:w1_q3_hint": "/assets/audio/w1_q3_hint.mp3",
  "A town had four thousand people. Now it has four thousand six hundred people. What is the increase?": "/assets/audio/w1_q4_prompt.mp3",
  "key:w1_q4_prompt": "/assets/audio/w1_q4_prompt.mp3",
  "Increase equals New minus Original. Subtract four thousand six hundred minus four thousand.": "/assets/audio/w1_q4_hint.mp3",
  "key:w1_q4_hint": "/assets/audio/w1_q4_hint.mp3",
  "A plant was thirty centimetres tall. It grows to forty-five centimetres. What is the increase in height?": "/assets/audio/w1_q5_prompt.mp3",
  "key:w1_q5_prompt": "/assets/audio/w1_q5_prompt.mp3",
  "Increase equals New height minus Original height. Subtract forty-five minus thirty.": "/assets/audio/w1_q5_hint.mp3",
  "key:w1_q5_hint": "/assets/audio/w1_q5_hint.mp3",
  "A ticket costs forty dollars. After a price rise the increase is twelve dollars. What is the new price?": "/assets/audio/w1_q6_prompt.mp3",
  "key:w1_q6_prompt": "/assets/audio/w1_q6_prompt.mp3",
  "New equals Original plus Increase. Add forty plus twelve.": "/assets/audio/w1_q6_hint.mp3",
  "key:w1_q6_hint": "/assets/audio/w1_q6_hint.mp3",
  "A bag costs ninety dollars. In a sale the decrease is fifteen dollars. What is the new price?": "/assets/audio/w1_q7_prompt.mp3",
  "key:w1_q7_prompt": "/assets/audio/w1_q7_prompt.mp3",
  "New equals Original minus Decrease. Subtract ninety minus fifteen.": "/assets/audio/w1_q7_hint.mp3",
  "key:w1_q7_hint": "/assets/audio/w1_q7_hint.mp3",
  "A price goes from ninety dollars to seventy-five dollars. Which one describes the change?": "/assets/audio/w1_q8_prompt.mp3",
  "key:w1_q8_prompt": "/assets/audio/w1_q8_prompt.mp3",
  "The new price is smaller than the original price. Then find the difference.": "/assets/audio/w1_q8_hint.mp3",
  "key:w1_q8_hint": "/assets/audio/w1_q8_hint.mp3",
  "A phone costs six hundred dollars. After an update the price is six hundred fifty dollars. Which one describes the change?": "/assets/audio/w1_q9_prompt.mp3",
  "key:w1_q9_prompt": "/assets/audio/w1_q9_prompt.mp3",
  "The new price is bigger than the original price. Then find the difference.": "/assets/audio/w1_q9_hint.mp3",
  "key:w1_q9_hint": "/assets/audio/w1_q9_hint.mp3",
  "A class had thirty students. Now there are twenty-seven students. What is the decrease?": "/assets/audio/w1_q10_prompt.mp3",
  "key:w1_q10_prompt": "/assets/audio/w1_q10_prompt.mp3",
  "Decrease equals Original minus New. Subtract thirty minus twenty-seven.": "/assets/audio/w1_q10_hint.mp3",
  "key:w1_q10_hint": "/assets/audio/w1_q10_hint.mp3",
  "What is ten percent of two hundred dollars?": "/assets/audio/w2_q1_prompt.mp3",
  "key:w2_q1_prompt": "/assets/audio/w2_q1_prompt.mp3",
  "Ten percent means ten out of one hundred. Divide two hundred dollars by ten.": "/assets/audio/w2_q1_hint.mp3",
  "key:w2_q1_hint": "/assets/audio/w2_q1_hint.mp3",
  "A bag of rice weighs sixty-four kilograms. Fifty percent of it is used. How many kilograms are used?": "/assets/audio/w2_q2_prompt.mp3",
  "key:w2_q2_prompt": "/assets/audio/w2_q2_prompt.mp3",
  "Fifty percent is half. Divide sixty-four by two.": "/assets/audio/w2_q2_hint.mp3",
  "key:w2_q2_hint": "/assets/audio/w2_q2_hint.mp3",
  "What is twenty-five percent of eighty dollars?": "/assets/audio/w2_q3_prompt.mp3",
  "key:w2_q3_prompt": "/assets/audio/w2_q3_prompt.mp3",
  "Twenty-five percent is one quarter. Divide eighty dollars by four.": "/assets/audio/w2_q3_hint.mp3",
  "key:w2_q3_hint": "/assets/audio/w2_q3_hint.mp3",
  "A school has one hundred fifty students. Twenty percent take the bus. How many students take the bus?": "/assets/audio/w2_q4_prompt.mp3",
  "key:w2_q4_prompt": "/assets/audio/w2_q4_prompt.mp3",
  "Ten percent of one hundred fifty is fifteen. So twenty percent is double that.": "/assets/audio/w2_q4_hint.mp3",
  "key:w2_q4_hint": "/assets/audio/w2_q4_hint.mp3",
  "A meal costs one hundred twenty dollars. The service charge is five percent. How much is the service charge?": "/assets/audio/w2_q5_prompt.mp3",
  "key:w2_q5_prompt": "/assets/audio/w2_q5_prompt.mp3",
  "Ten percent of one hundred twenty dollars is twelve dollars. So five percent is half of that.": "/assets/audio/w2_q5_hint.mp3",
  "key:w2_q5_hint": "/assets/audio/w2_q5_hint.mp3",
  "A ribbon is forty centimetres long. Seventy-five percent of it is painted red. How many centimetres are red?": "/assets/audio/w2_q6_prompt.mp3",
  "key:w2_q6_prompt": "/assets/audio/w2_q6_prompt.mp3",
  "Seventy-five percent is three quarters. One quarter of forty is ten.": "/assets/audio/w2_q6_hint.mp3",
  "key:w2_q6_hint": "/assets/audio/w2_q6_hint.mp3",
  "Sam has ninety dollars and saves thirty percent of it. How much does Sam save?": "/assets/audio/w2_q7_prompt.mp3",
  "key:w2_q7_prompt": "/assets/audio/w2_q7_prompt.mp3",
  "Ten percent of ninety dollars is nine dollars. So thirty percent is three times that.": "/assets/audio/w2_q7_hint.mp3",
  "key:w2_q7_hint": "/assets/audio/w2_q7_hint.mp3",
  "A class wants to raise two hundred fifty dollars. So far forty percent has been raised. How much is that?": "/assets/audio/w2_q8_prompt.mp3",
  "key:w2_q8_prompt": "/assets/audio/w2_q8_prompt.mp3",
  "Ten percent of two hundred fifty dollars is twenty-five dollars. So forty percent is four times that.": "/assets/audio/w2_q8_hint.mp3",
  "key:w2_q8_hint": "/assets/audio/w2_q8_hint.mp3",
  "A pack has sixty stickers. Fifteen percent are gold. How many gold stickers are there?": "/assets/audio/w2_q9_prompt.mp3",
  "key:w2_q9_prompt": "/assets/audio/w2_q9_prompt.mp3",
  "Ten percent of sixty is six and five percent is three. Add them: six plus three.": "/assets/audio/w2_q9_hint.mp3",
  "key:w2_q9_hint": "/assets/audio/w2_q9_hint.mp3",
  "A trail is one hundred fifty kilometres long. Hikers have walked sixty percent of it. How many kilometres is that?": "/assets/audio/w2_q10_prompt.mp3",
  "key:w2_q10_prompt": "/assets/audio/w2_q10_prompt.mp3",
  "Ten percent of one hundred fifty is fifteen. So sixty percent is six times that.": "/assets/audio/w2_q10_hint.mp3",
  "key:w2_q10_hint": "/assets/audio/w2_q10_hint.mp3",
  "A video game costs fifty dollars. The price rises by twenty percent. What is the new price?": "/assets/audio/w3_q1_prompt.mp3",
  "key:w3_q1_prompt": "/assets/audio/w3_q1_prompt.mp3",
  "Find twenty percent of fifty first. Then ADD it to the original.": "/assets/audio/w3_q1_hint.mp3",
  "key:w3_q1_hint": "/assets/audio/w3_q1_hint.mp3",
  "A bike helmet costs eighty dollars. Its price goes up by twenty-five percent. Find the new price.": "/assets/audio/w3_q2_prompt.mp3",
  "key:w3_q2_prompt": "/assets/audio/w3_q2_prompt.mp3",
  "Find twenty-five percent of eighty first. Then ADD it to the original.": "/assets/audio/w3_q2_hint.mp3",
  "key:w3_q2_hint": "/assets/audio/w3_q2_hint.mp3",
  "A club has two hundred members. The number of members rises by ten percent. How many members are there now?": "/assets/audio/w3_q3_prompt.mp3",
  "key:w3_q3_prompt": "/assets/audio/w3_q3_prompt.mp3",
  "Find ten percent of two hundred first. Then ADD it to the original.": "/assets/audio/w3_q3_hint.mp3",
  "key:w3_q3_hint": "/assets/audio/w3_q3_hint.mp3",
  "A plant is forty centimetres tall. It grows fifty percent taller. What is its new height?": "/assets/audio/w3_q4_prompt.mp3",
  "key:w3_q4_prompt": "/assets/audio/w3_q4_prompt.mp3",
  "Find fifty percent of forty first. Then ADD it to the original.": "/assets/audio/w3_q4_hint.mp3",
  "key:w3_q4_hint": "/assets/audio/w3_q4_hint.mp3",
  "A phone plan costs one hundred twenty dollars a year. The price rises by five percent. Find the new cost.": "/assets/audio/w3_q5_prompt.mp3",
  "key:w3_q5_prompt": "/assets/audio/w3_q5_prompt.mp3",
  "Find five percent of one hundred twenty first. Then ADD it to the original.": "/assets/audio/w3_q5_hint.mp3",
  "key:w3_q5_hint": "/assets/audio/w3_q5_hint.mp3",
  "Ella has sixty dollars in savings. Her savings increase by fifteen percent. How much does she have now?": "/assets/audio/w3_q6_prompt.mp3",
  "key:w3_q6_prompt": "/assets/audio/w3_q6_prompt.mp3",
  "Find fifteen percent of sixty first. Then ADD it to the original.": "/assets/audio/w3_q6_hint.mp3",
  "key:w3_q6_hint": "/assets/audio/w3_q6_hint.mp3",
  "A library has one hundred fifty books. The number of books increases by forty percent. How many books are there now?": "/assets/audio/w3_q7_prompt.mp3",
  "key:w3_q7_prompt": "/assets/audio/w3_q7_prompt.mp3",
  "Find forty percent of one hundred fifty first. Then ADD it to the original.": "/assets/audio/w3_q7_hint.mp3",
  "key:w3_q7_hint": "/assets/audio/w3_q7_hint.mp3",
  "A concert ticket costs ninety dollars. The price goes up by ten percent. What is the new price?": "/assets/audio/w3_q8_prompt.mp3",
  "key:w3_q8_prompt": "/assets/audio/w3_q8_prompt.mp3",
  "Find ten percent of ninety first. Then ADD it to the original.": "/assets/audio/w3_q8_hint.mp3",
  "key:w3_q8_hint": "/assets/audio/w3_q8_hint.mp3",
  "A farm picked two hundred forty kilograms of mangoes. This year it picks twenty-five percent more. How many kilograms is that?": "/assets/audio/w3_q9_prompt.mp3",
  "key:w3_q9_prompt": "/assets/audio/w3_q9_prompt.mp3",
  "Find twenty-five percent of two hundred forty first. Then ADD it to the original.": "/assets/audio/w3_q9_hint.mp3",
  "key:w3_q9_hint": "/assets/audio/w3_q9_hint.mp3",
  "A factory makes three hundred toys a day. Its output rises by twelve percent. How many toys does it make now?": "/assets/audio/w3_q10_prompt.mp3",
  "key:w3_q10_prompt": "/assets/audio/w3_q10_prompt.mp3",
  "Find twelve percent of three hundred first. Then ADD it to the original.": "/assets/audio/w3_q10_hint.mp3",
  "key:w3_q10_hint": "/assets/audio/w3_q10_hint.mp3",
  "A backpack costs eighty dollars. It is on sale for twenty-five percent off. What is the sale price?": "/assets/audio/w4_q1_prompt.mp3",
  "key:w4_q1_prompt": "/assets/audio/w4_q1_prompt.mp3",
  "Find twenty-five percent of eighty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q1_hint.mp3",
  "key:w4_q1_hint": "/assets/audio/w4_q1_hint.mp3",
  "A cap costs fifty dollars. There is a twenty percent discount. How much do you pay?": "/assets/audio/w4_q2_prompt.mp3",
  "key:w4_q2_prompt": "/assets/audio/w4_q2_prompt.mp3",
  "Find twenty percent of fifty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q2_hint.mp3",
  "key:w4_q2_hint": "/assets/audio/w4_q2_hint.mp3",
  "A cinema has two hundred seats. Ten percent of the seats are broken. How many seats still work?": "/assets/audio/w4_q3_prompt.mp3",
  "key:w4_q3_prompt": "/assets/audio/w4_q3_prompt.mp3",
  "Find ten percent of two hundred first. Then SUBTRACT it from the original.": "/assets/audio/w4_q3_hint.mp3",
  "key:w4_q3_hint": "/assets/audio/w4_q3_hint.mp3",
  "A pair of trainers costs one hundred twenty dollars. It is half price (fifty percent off). What is the sale price?": "/assets/audio/w4_q4_prompt.mp3",
  "key:w4_q4_prompt": "/assets/audio/w4_q4_prompt.mp3",
  "Find fifty percent of one hundred twenty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q4_hint.mp3",
  "key:w4_q4_hint": "/assets/audio/w4_q4_hint.mp3",
  "A book costs sixty dollars. It is reduced by fifteen percent. What is the new price?": "/assets/audio/w4_q5_prompt.mp3",
  "key:w4_q5_prompt": "/assets/audio/w4_q5_prompt.mp3",
  "Find fifteen percent of sixty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q5_hint.mp3",
  "key:w4_q5_hint": "/assets/audio/w4_q5_hint.mp3",
  "A tank holds one hundred fifty litres of water. Twenty percent is used. How many litres are left?": "/assets/audio/w4_q6_prompt.mp3",
  "key:w4_q6_prompt": "/assets/audio/w4_q6_prompt.mp3",
  "Find twenty percent of one hundred fifty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q6_hint.mp3",
  "key:w4_q6_hint": "/assets/audio/w4_q6_hint.mp3",
  "A jacket costs ninety dollars. It is reduced by thirty percent. Find the new price.": "/assets/audio/w4_q7_prompt.mp3",
  "key:w4_q7_prompt": "/assets/audio/w4_q7_prompt.mp3",
  "Find thirty percent of ninety first. Then SUBTRACT it from the original.": "/assets/audio/w4_q7_hint.mp3",
  "key:w4_q7_hint": "/assets/audio/w4_q7_hint.mp3",
  "A tablet costs two hundred fifty dollars. There is a forty percent discount. What is the sale price?": "/assets/audio/w4_q8_prompt.mp3",
  "key:w4_q8_prompt": "/assets/audio/w4_q8_prompt.mp3",
  "Find forty percent of two hundred fifty first. Then SUBTRACT it from the original.": "/assets/audio/w4_q8_hint.mp3",
  "key:w4_q8_hint": "/assets/audio/w4_q8_hint.mp3",
  "A village has four hundred people. The population falls by five percent. How many people live there now?": "/assets/audio/w4_q9_prompt.mp3",
  "key:w4_q9_prompt": "/assets/audio/w4_q9_prompt.mp3",
  "Find five percent of four hundred first. Then SUBTRACT it from the original.": "/assets/audio/w4_q9_hint.mp3",
  "key:w4_q9_hint": "/assets/audio/w4_q9_hint.mp3",
  "A dinner costs seventy-five dollars. A coupon gives twenty percent off. How much do you pay?": "/assets/audio/w4_q10_prompt.mp3",
  "key:w4_q10_prompt": "/assets/audio/w4_q10_prompt.mp3",
  "Find twenty percent of seventy-five first. Then SUBTRACT it from the original.": "/assets/audio/w4_q10_hint.mp3",
  "key:w4_q10_hint": "/assets/audio/w4_q10_hint.mp3",
  "A video game's price rises from forty dollars to fifty dollars. What is the percentage increase?": "/assets/audio/w5_q1_prompt.mp3",
  "key:w5_q1_prompt": "/assets/audio/w5_q1_prompt.mp3",
  "Step one: change equals New minus Original. Step two: divide the change by the ORIGINAL, then times one hundred.": "/assets/audio/w5_q10_hint.mp3",
  "key:w5_q1_hint": "/assets/audio/w5_q1_hint.mp3",
  "A jacket's price falls from eighty dollars to sixty-eight dollars. What is the percentage decrease?": "/assets/audio/w5_q2_prompt.mp3",
  "key:w5_q2_prompt": "/assets/audio/w5_q2_prompt.mp3",
  "Step one: change equals Original minus New. Step two: divide the change by the ORIGINAL, then times one hundred.": "/assets/audio/w5_q9_hint.mp3",
  "key:w5_q2_hint": "/assets/audio/w5_q2_hint.mp3",
  "A club grows from fifty members to seventy-five members. Find the percentage increase.": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_prompt": "/assets/audio/w5_q3_prompt.mp3",
  "key:w5_q3_hint": "/assets/audio/w5_q3_hint.mp3",
  "A water tank drops from two hundred litres to one hundred fifty litres. Find the percentage decrease.": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q4_prompt": "/assets/audio/w5_q4_prompt.mp3",
  "key:w5_q4_hint": "/assets/audio/w5_q4_hint.mp3",
  "A sunflower grows from sixty centimetres to seventy-two centimetres. What is the percentage increase?": "/assets/audio/w5_q5_prompt.mp3",
  "key:w5_q5_prompt": "/assets/audio/w5_q5_prompt.mp3",
  "key:w5_q5_hint": "/assets/audio/w5_q5_hint.mp3",
  "A cinema audience falls from one hundred twenty people to eighty-four people. What is the percentage decrease?": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_prompt": "/assets/audio/w5_q6_prompt.mp3",
  "key:w5_q6_hint": "/assets/audio/w5_q6_hint.mp3",
  "A bus fare rises from twenty-five dollars to thirty-five dollars. What is the percentage increase?": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q7_prompt": "/assets/audio/w5_q7_prompt.mp3",
  "key:w5_q7_hint": "/assets/audio/w5_q7_hint.mp3",
  "A pupil's score goes up from ninety marks to ninety-nine marks. What is the percentage increase?": "/assets/audio/w5_q8_prompt.mp3",
  "key:w5_q8_prompt": "/assets/audio/w5_q8_prompt.mp3",
  "key:w5_q8_hint": "/assets/audio/w5_q8_hint.mp3",
  "Screen time is cut from one hundred fifty minutes to one hundred twenty minutes a day. What is the percentage decrease?": "/assets/audio/w5_q9_prompt.mp3",
  "key:w5_q9_prompt": "/assets/audio/w5_q9_prompt.mp3",
  "key:w5_q9_hint": "/assets/audio/w5_q9_hint.mp3",
  "A pumpkin's weight grows from forty kilograms to sixty-four kilograms. What is the percentage increase?": "/assets/audio/w5_q10_prompt.mp3",
  "key:w5_q10_prompt": "/assets/audio/w5_q10_prompt.mp3",
  "key:w5_q10_hint": "/assets/audio/w5_q10_hint.mp3",
  "Which multiplier represents a twenty percent increase?": "/assets/audio/w6_q1_prompt.mp3",
  "key:w6_q1_prompt": "/assets/audio/w6_q1_prompt.mp3",
  "An increase is one hundred percent plus twenty percent equals one hundred twenty percent. As a decimal, one hundred twenty percent equals one point two.": "/assets/audio/w6_q1_hint.mp3",
  "key:w6_q1_hint": "/assets/audio/w6_q1_hint.mp3",
  "Which multiplier represents a twenty-five percent decrease?": "/assets/audio/w6_q2_prompt.mp3",
  "key:w6_q2_prompt": "/assets/audio/w6_q2_prompt.mp3",
  "A decrease is one hundred percent minus twenty-five percent equals seventy-five percent. As a decimal, seventy-five percent equals zero point seven five.": "/assets/audio/w6_q2_hint.mp3",
  "key:w6_q2_hint": "/assets/audio/w6_q2_hint.mp3",
  "Increase sixty dollars by fifteen percent using the multiplier times one point one five. What is the new amount?": "/assets/audio/w6_q3_prompt.mp3",
  "key:w6_q3_prompt": "/assets/audio/w6_q3_prompt.mp3",
  "Multiply the original by one point one five: sixty times one point one five.": "/assets/audio/w6_q3_hint.mp3",
  "key:w6_q3_hint": "/assets/audio/w6_q3_hint.mp3",
  "Decrease two hundred forty by thirty percent using the multiplier times zero point seven. What is the new amount?": "/assets/audio/w6_q4_prompt.mp3",
  "key:w6_q4_prompt": "/assets/audio/w6_q4_prompt.mp3",
  "Multiply the original by zero point seven: two hundred forty times zero point seven.": "/assets/audio/w6_q4_hint.mp3",
  "key:w6_q4_hint": "/assets/audio/w6_q4_hint.mp3",
  "Which multiplier represents a five percent increase?": "/assets/audio/w6_q5_prompt.mp3",
  "key:w6_q5_prompt": "/assets/audio/w6_q5_prompt.mp3",
  "One hundred percent plus five percent equals one hundred five percent. As a decimal, one hundred five percent equals one point zero five.": "/assets/audio/w6_q5_hint.mp3",
  "key:w6_q5_hint": "/assets/audio/w6_q5_hint.mp3",
  "A price is multiplied by zero point nine. What percentage change is that?": "/assets/audio/w6_q6_prompt.mp3",
  "key:w6_q6_prompt": "/assets/audio/w6_q6_prompt.mp3",
  "Zero point nine means ninety percent of the original is left. Is that more or less than one hundred percent?": "/assets/audio/w6_q6_hint.mp3",
  "key:w6_q6_hint": "/assets/audio/w6_q6_hint.mp3",
  "An amount is multiplied by one point three five. What percentage change is that?": "/assets/audio/w6_q7_prompt.mp3",
  "key:w6_q7_prompt": "/assets/audio/w6_q7_prompt.mp3",
  "One point three five equals one hundred thirty-five percent. Is that more or less than one hundred percent?": "/assets/audio/w6_q7_hint.mp3",
  "key:w6_q7_hint": "/assets/audio/w6_q7_hint.mp3",
  "An amount is multiplied by zero point six. What percentage change is that?": "/assets/audio/w6_q8_prompt.mp3",
  "key:w6_q8_prompt": "/assets/audio/w6_q8_prompt.mp3",
  "Zero point six equals sixty percent. How much is missing from one hundred percent?": "/assets/audio/w6_q8_hint.mp3",
  "key:w6_q8_hint": "/assets/audio/w6_q8_hint.mp3",
  "Increase one hundred fifty by eight percent using a multiplier. What is the new amount?": "/assets/audio/w6_q9_prompt.mp3",
  "key:w6_q9_prompt": "/assets/audio/w6_q9_prompt.mp3",
  "The multiplier for an eight percent increase is one point zero eight. Calculate one hundred fifty times one point zero eight.": "/assets/audio/w6_q9_hint.mp3",
  "key:w6_q9_hint": "/assets/audio/w6_q9_hint.mp3",
  "Decrease three hundred fifty by twelve percent using a multiplier. What is the new amount?": "/assets/audio/w6_q10_prompt.mp3",
  "key:w6_q10_prompt": "/assets/audio/w6_q10_prompt.mp3",
  "The multiplier for a twelve percent decrease is zero point eight eight. Calculate three hundred fifty times zero point eight eight.": "/assets/audio/w6_q10_hint.mp3",
  "key:w6_q10_hint": "/assets/audio/w6_q10_hint.mp3",
  "A game costs one hundred dollars. The shop raises the price by twenty percent. Then a sale cuts the new price by twenty percent. What is the final price?": "/assets/audio/w7_q1_prompt.mp3",
  "key:w7_q1_prompt": "/assets/audio/w7_q1_prompt.mp3",
  "Do it in TWO steps. The second percentage is taken from the NEW amount, not from the start.": "/assets/audio/w7_q10_hint.mp3",
  "key:w7_q1_hint": "/assets/audio/w7_q1_hint.mp3",
  "A toy costs two hundred dollars. Its price goes up by fifty percent, then down by fifty percent. How does the final price compare with the start?": "/assets/audio/w7_q2_prompt.mp3",
  "key:w7_q2_prompt": "/assets/audio/w7_q2_prompt.mp3",
  "Use multipliers: multiply the two together and see whether the result is more than, less than, or equal to one.": "/assets/audio/w7_q4_hint.mp3",
  "key:w7_q2_hint": "/assets/audio/w7_q2_hint.mp3",
  "A jacket costs one hundred dollars. A sale takes off twenty percent. After the sale the new price goes up by twenty percent. What is the final price?": "/assets/audio/w7_q3_prompt.mp3",
  "key:w7_q3_prompt": "/assets/audio/w7_q3_prompt.mp3",
  "key:w7_q3_hint": "/assets/audio/w7_q3_hint.mp3",
  "A watch costs eighty dollars. Its price goes up by twenty-five percent, then down by twenty percent. How does the final price compare with the start?": "/assets/audio/w7_q4_prompt.mp3",
  "key:w7_q4_prompt": "/assets/audio/w7_q4_prompt.mp3",
  "key:w7_q4_hint": "/assets/audio/w7_q4_hint.mp3",
  "A card costs fifty dollars. Its price doubles (up one hundred percent) and then is cut by fifty percent. What is the final price?": "/assets/audio/w7_q5_prompt.mp3",
  "key:w7_q5_prompt": "/assets/audio/w7_q5_prompt.mp3",
  "key:w7_q5_hint": "/assets/audio/w7_q5_hint.mp3",
  "A town has two hundred people. Its population grows ten percent in year one and ten percent again in year two. How many people live there after two years?": "/assets/audio/w7_q6_prompt.mp3",
  "key:w7_q6_prompt": "/assets/audio/w7_q6_prompt.mp3",
  "key:w7_q6_hint": "/assets/audio/w7_q6_hint.mp3",
  "A bike costs four hundred dollars. It is reduced by twenty-five percent, and then the new price is reduced by another twenty percent. What is the final price?": "/assets/audio/w7_q7_prompt.mp3",
  "key:w7_q7_prompt": "/assets/audio/w7_q7_prompt.mp3",
  "key:w7_q7_hint": "/assets/audio/w7_q7_hint.mp3",
  "A bag costs sixty dollars. The price rises by fifty percent and then falls by twenty percent. What is the final price?": "/assets/audio/w7_q8_prompt.mp3",
  "key:w7_q8_prompt": "/assets/audio/w7_q8_prompt.mp3",
  "key:w7_q8_hint": "/assets/audio/w7_q8_hint.mp3",
  "Amy has five hundred dollars in a fund. It falls by ten percent one month and rises by ten percent the next month. How much is in the fund now?": "/assets/audio/w7_q9_prompt.mp3",
  "key:w7_q9_prompt": "/assets/audio/w7_q9_prompt.mp3",
  "key:w7_q9_hint": "/assets/audio/w7_q9_hint.mp3",
  "A pond has one hundred twenty fish. The number of fish grows by twenty-five percent, then grows by another twenty percent. How many fish are there now?": "/assets/audio/w7_q10_prompt.mp3",
  "key:w7_q10_prompt": "/assets/audio/w7_q10_prompt.mp3",
  "key:w7_q10_hint": "/assets/audio/w7_q10_hint.mp3",
  "After a twenty percent price rise, a video game costs sixty dollars. What was the original price?": "/assets/audio/w8_q1_prompt.mp3",
  "key:w8_q1_prompt": "/assets/audio/w8_q1_prompt.mp3",
  "The new amount is one hundred twenty percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by one point two.": "/assets/audio/w8_q1_hint.mp3",
  "key:w8_q1_hint": "/assets/audio/w8_q1_hint.mp3",
  "After a twenty-five percent price rise, a helmet costs one hundred dollars. What was the original price?": "/assets/audio/w8_q2_prompt.mp3",
  "key:w8_q2_prompt": "/assets/audio/w8_q2_prompt.mp3",
  "The new amount is one hundred twenty-five percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by one point two five.": "/assets/audio/w8_q2_hint.mp3",
  "key:w8_q2_hint": "/assets/audio/w8_q2_hint.mp3",
  "A bag costs eighty dollars after a twenty percent discount. What was the original price?": "/assets/audio/w8_q3_prompt.mp3",
  "key:w8_q3_prompt": "/assets/audio/w8_q3_prompt.mp3",
  "The new amount is eighty percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by zero point eight.": "/assets/audio/w8_q3_hint.mp3",
  "key:w8_q3_hint": "/assets/audio/w8_q3_hint.mp3",
  "A watch costs one hundred fifty dollars after a twenty-five percent discount. What was the original price?": "/assets/audio/w8_q4_prompt.mp3",
  "key:w8_q4_prompt": "/assets/audio/w8_q4_prompt.mp3",
  "The new amount is seventy-five percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by zero point seven five.": "/assets/audio/w8_q4_hint.mp3",
  "key:w8_q4_hint": "/assets/audio/w8_q4_hint.mp3",
  "A tree is ninety centimetres tall after growing fifty percent taller. How tall was it before?": "/assets/audio/w8_q5_prompt.mp3",
  "key:w8_q5_prompt": "/assets/audio/w8_q5_prompt.mp3",
  "The new amount is one hundred fifty percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by one point five.": "/assets/audio/w8_q5_hint.mp3",
  "key:w8_q5_hint": "/assets/audio/w8_q5_hint.mp3",
  "A ticket costs forty-five dollars after a ten percent discount. What was the original price?": "/assets/audio/w8_q6_prompt.mp3",
  "key:w8_q6_prompt": "/assets/audio/w8_q6_prompt.mp3",
  "The new amount is ninety percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by zero point nine.": "/assets/audio/w8_q6_hint.mp3",
  "key:w8_q6_hint": "/assets/audio/w8_q6_hint.mp3",
  "After a ten percent pay rise, Kim earns one hundred sixty-five dollars a week. What did Kim earn before the rise?": "/assets/audio/w8_q7_prompt.mp3",
  "key:w8_q7_prompt": "/assets/audio/w8_q7_prompt.mp3",
  "The new amount is one hundred ten percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by one point one.": "/assets/audio/w8_q7_hint.mp3",
  "key:w8_q7_hint": "/assets/audio/w8_q7_hint.mp3",
  "A jacket costs seventy-two dollars after forty percent off. What was the original price?": "/assets/audio/w8_q8_prompt.mp3",
  "key:w8_q8_prompt": "/assets/audio/w8_q8_prompt.mp3",
  "The new amount is sixty percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by zero point six.": "/assets/audio/w8_q8_hint.mp3",
  "key:w8_q8_hint": "/assets/audio/w8_q8_hint.mp3",
  "A library has two hundred sixty books after a thirty percent increase. How many books did it have before?": "/assets/audio/w8_q9_prompt.mp3",
  "key:w8_q9_prompt": "/assets/audio/w8_q9_prompt.mp3",
  "The new amount is one hundred thirty percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by one point three.": "/assets/audio/w8_q9_hint.mp3",
  "key:w8_q9_hint": "/assets/audio/w8_q9_hint.mp3",
  "A phone costs two hundred ten dollars after thirty percent off. What was the original price?": "/assets/audio/w8_q10_prompt.mp3",
  "key:w8_q10_prompt": "/assets/audio/w8_q10_prompt.mp3",
  "The new amount is seventy percent of the original. Find one percent or ten percent first, then scale up to one hundred percent. Or divide by zero point seven.": "/assets/audio/w8_q10_hint.mp3",
  "key:w8_q10_hint": "/assets/audio/w8_q10_hint.mp3",
  "A town's population rose from eight thousand to nine thousand two hundred. What is the percentage increase?": "/assets/audio/w9_q1_prompt.mp3",
  "key:w9_q1_prompt": "/assets/audio/w9_q1_prompt.mp3",
  "Change equals nine thousand two hundred minus eight thousand. Divide by the ORIGINAL eight thousand, then times one hundred.": "/assets/audio/w9_q1_hint.mp3",
  "key:w9_q1_hint": "/assets/audio/w9_q1_hint.mp3",
  "A water tank held two hundred fifty litres. It now holds two hundred litres. What is the percentage decrease?": "/assets/audio/w9_q2_prompt.mp3",
  "key:w9_q2_prompt": "/assets/audio/w9_q2_prompt.mp3",
  "Change equals two hundred fifty minus two hundred. Divide by the ORIGINAL two hundred fifty, then times one hundred.": "/assets/audio/w9_q2_hint.mp3",
  "key:w9_q2_hint": "/assets/audio/w9_q2_hint.mp3",
  "Mia saved forty dollars in January. In February she saved twenty-five percent more. How much did she save in February?": "/assets/audio/w9_q3_prompt.mp3",
  "key:w9_q3_prompt": "/assets/audio/w9_q3_prompt.mp3",
  "Twenty-five percent of forty dollars is ten dollars. Then add it to forty dollars.": "/assets/audio/w9_q3_hint.mp3",
  "key:w9_q3_hint": "/assets/audio/w9_q3_hint.mp3",
  "There are forty pupils in a class. Ten percent are absent. How many pupils are present?": "/assets/audio/w9_q4_prompt.mp3",
  "key:w9_q4_prompt": "/assets/audio/w9_q4_prompt.mp3",
  "Ten percent of forty is four pupils absent. Subtract from forty.": "/assets/audio/w9_q4_hint.mp3",
  "key:w9_q4_hint": "/assets/audio/w9_q4_hint.mp3",
  "Tom is one hundred fifty centimetres tall. He grows four percent taller. How tall is Tom now?": "/assets/audio/w9_q5_prompt.mp3",
  "key:w9_q5_prompt": "/assets/audio/w9_q5_prompt.mp3",
  "One percent of one hundred fifty is one point five centimetres. So four percent is six centimetres. Then add it.": "/assets/audio/w9_q5_hint.mp3",
  "key:w9_q5_hint": "/assets/audio/w9_q5_hint.mp3",
  "Jeans cost sixty dollars. There is a thirty percent discount. How much do you pay?": "/assets/audio/w9_q6_prompt.mp3",
  "key:w9_q6_prompt": "/assets/audio/w9_q6_prompt.mp3",
  "You pay seventy percent of the price (one hundred percent minus thirty percent). Find seventy percent of sixty.": "/assets/audio/w9_q6_hint.mp3",
  "key:w9_q6_hint": "/assets/audio/w9_q6_hint.mp3",
  "A ticket cost twenty dollars last year and twenty-five dollars this year. What is the percentage increase?": "/assets/audio/w9_q7_prompt.mp3",
  "key:w9_q7_prompt": "/assets/audio/w9_q7_prompt.mp3",
  "Change equals five dollars. Divide by last year’s price twenty dollars (the ORIGINAL).": "/assets/audio/w9_q7_hint.mp3",
  "key:w9_q7_hint": "/assets/audio/w9_q7_hint.mp3",
  "An electricity bill of one hundred twenty dollars falls by fifteen percent. What is the new bill?": "/assets/audio/w9_q8_prompt.mp3",
  "key:w9_q8_prompt": "/assets/audio/w9_q8_prompt.mp3",
  "Ten percent of one hundred twenty is twelve and five percent is six, so fifteen percent is eighteen. Then subtract.": "/assets/audio/w9_q8_hint.mp3",
  "key:w9_q8_hint": "/assets/audio/w9_q8_hint.mp3",
  "A hamster weighs two hundred grams. A month later it weighs two hundred sixty grams. What is the percentage increase?": "/assets/audio/w9_q9_prompt.mp3",
  "key:w9_q9_prompt": "/assets/audio/w9_q9_prompt.mp3",
  "Change equals sixty grams. Divide by the ORIGINAL two hundred grams, then times one hundred.": "/assets/audio/w9_q9_hint.mp3",
  "key:w9_q9_hint": "/assets/audio/w9_q9_hint.mp3",
  "A school has five hundred students. Eight percent of them leave. How many students remain?": "/assets/audio/w9_q10_prompt.mp3",
  "key:w9_q10_prompt": "/assets/audio/w9_q10_prompt.mp3",
  "One percent of five hundred is five, so eight percent is forty students. Then subtract.": "/assets/audio/w9_q10_hint.mp3",
  "key:w9_q10_hint": "/assets/audio/w9_q10_hint.mp3",
  "A bag costs eighty dollars. It is on sale at twenty-five percent off. Then a coupon takes a further ten dollars off. What is the final price?": "/assets/audio/w10_q1_prompt.mp3",
  "key:w10_q1_prompt": "/assets/audio/w10_q1_prompt.mp3",
  "First find the price after twenty-five percent off. Then subtract the ten dollars coupon.": "/assets/audio/w10_q1_hint.mp3",
  "key:w10_q1_hint": "/assets/audio/w10_q1_hint.mp3",
  "After a twenty percent discount, a jacket costs ninety-six dollars. How much was the discount in dollars?": "/assets/audio/w10_q2_prompt.mp3",
  "key:w10_q2_prompt": "/assets/audio/w10_q2_prompt.mp3",
  "Ninety-six dollars is eighty percent of the original. Find the original first, then subtract ninety-six dollars.": "/assets/audio/w10_q2_hint.mp3",
  "key:w10_q2_hint": "/assets/audio/w10_q2_hint.mp3",
  "Ali has three hundred dollars. Ben has twenty percent more than Ali. How much do they have altogether?": "/assets/audio/w10_q3_prompt.mp3",
  "key:w10_q3_prompt": "/assets/audio/w10_q3_prompt.mp3",
  "Find Ben’s money first (three hundred plus twenty percent of three hundred). Then add Ali’s three hundred dollars.": "/assets/audio/w10_q3_hint.mp3",
  "key:w10_q3_hint": "/assets/audio/w10_q3_hint.mp3",
  "A shirt costs forty dollars after a twenty percent discount. What is the total cost of three such shirts at the ORIGINAL price?": "/assets/audio/w10_q4_prompt.mp3",
  "key:w10_q4_prompt": "/assets/audio/w10_q4_prompt.mp3",
  "Forty dollars is eighty percent of the original. Find the original price of one shirt, then times three.": "/assets/audio/w10_q4_hint.mp3",
  "key:w10_q4_hint": "/assets/audio/w10_q4_hint.mp3",
  "Tank A has forty percent more water than Tank B. Tank B has one hundred fifty litres. How many litres are in Tank A?": "/assets/audio/w10_q5_prompt.mp3",
  "key:w10_q5_prompt": "/assets/audio/w10_q5_prompt.mp3",
  "Tank B is the ORIGINAL (one hundred percent). Tank A is one hundred forty percent of it.": "/assets/audio/w10_q5_hint.mp3",
  "key:w10_q5_hint": "/assets/audio/w10_q5_hint.mp3",
  "After a twenty percent pay rise, Mister Lim earns three thousand six hundred dollars. What did he earn before the rise?": "/assets/audio/w10_q6_prompt.mp3",
  "key:w10_q6_prompt": "/assets/audio/w10_q6_prompt.mp3",
  "The new pay is one hundred twenty percent of the old pay. Divide three thousand six hundred dollars by one point two.": "/assets/audio/w10_q6_hint.mp3",
  "key:w10_q6_hint": "/assets/audio/w10_q6_hint.mp3",
  "A laptop's price falls from one thousand two hundred dollars to one thousand eighty dollars. What is the percentage decrease?": "/assets/audio/w10_q7_prompt.mp3",
  "key:w10_q7_prompt": "/assets/audio/w10_q7_prompt.mp3",
  "Change equals one hundred twenty dollars. Divide by the ORIGINAL one thousand two hundred dollars, then times one hundred.": "/assets/audio/w10_q7_hint.mp3",
  "key:w10_q7_hint": "/assets/audio/w10_q7_hint.mp3",
  "In Test one Sam scored sixty. In Test two he scored seventy-five. In Test three he scored twenty percent higher than in Test two. What was his Test three score?": "/assets/audio/w10_q8_prompt.mp3",
  "key:w10_q8_prompt": "/assets/audio/w10_q8_prompt.mp3",
  "Test three is compared with Test two (not Test one). Find twenty percent of seventy-five and add it.": "/assets/audio/w10_q8_hint.mp3",
  "key:w10_q8_hint": "/assets/audio/w10_q8_hint.mp3",
  "A number is increased by twenty percent to give ninety. What is the number?": "/assets/audio/w10_q9_prompt.mp3",
  "key:w10_q9_prompt": "/assets/audio/w10_q9_prompt.mp3",
  "Ninety is one hundred twenty percent of the number. Divide ninety by one point two.": "/assets/audio/w10_q9_hint.mp3",
  "key:w10_q9_hint": "/assets/audio/w10_q9_hint.mp3",
  "A toy costs fifty dollars. Its price is raised by twenty percent. Later a twenty percent discount is given on the new price. What is the final price?": "/assets/audio/w10_q10_prompt.mp3",
  "key:w10_q10_prompt": "/assets/audio/w10_q10_prompt.mp3",
  "Two steps. The discount is taken from the NEW price, not from fifty dollars.": "/assets/audio/w10_q10_hint.mp3",
  "key:w10_q10_hint": "/assets/audio/w10_q10_hint.mp3"
};
export default audioMap;
